language:  node_js
node_js: 
    - "8"
dist: trusty
sudo: required

branches:
    only:
    - master

install:
    - source travis_env_init.sh

script:
  -  hexo clean
  -  hexo g

after_success:
  -  hexo  deploy > /dev/null
